import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getWebsiteSettings } from "@/lib/adminServices";
import LayoutWrapper from "./components/LayoutWrapper";
import { CurrencyProvider } from "@/context/CurrencyContext";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ==========================
// ✅ Dynamic Metadata (favicon from DB)
// ==========================
export async function generateMetadata() {
  const res = await getWebsiteSettings();

  let settings = {};
  try {
    settings = JSON.parse(res?.plainsettings ?? "{}");
  } catch {
    settings = {};
  }

 return {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: settings.favicon?.startsWith("data:")
          ? settings.favicon
          : `${settings.favicon || ""}`,
        sizes: "32  x32",
      }
    ],
  },
};

}

// ==========================
// Root Layout Component
// ==========================
export default async function RootLayout({ children }) {
  const res = await getWebsiteSettings();

  let settings = {};
  try {
    settings = JSON.parse(res?.plainsettings ?? "{}");
  } catch {
    settings = {};
  }

  const h = await headers();
  const referer = h.get("referer");

  let path = "/";
  if (referer) {
    try {
      path = new URL(referer).pathname;
    } catch {}
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CurrencyProvider>
          <LayoutWrapper logo={settings.logo} siteName={settings.siteName}>
            {children}
          </LayoutWrapper>
        </CurrencyProvider>
      </body>
    </html>
  );
}
